version: '3.8'
services:
  labelstudio:
    image: heartexlabs/label-studio:latest
    ports:
      - '8081:8080'
    volumes:
      - .:/label-studio/data
    environment:
      LABEL_STUDIO_HOST: 'http://localhost:8081'